"""Claims agent review screen.

This is the human control surface, and it is the most important non-AI
component in the product. It is also the one that gets removed first, so it
has to earn that by proving itself.

Two things it must do:
  1. Show the reviewer everything the system used: photos, line items,
     reasoning, confidence arithmetic, flags. Nothing hidden.
  2. Capture overrides WITH A REASON CODE. Free text cannot be aggregated,
     and aggregation is the entire point — override reasons are the training
     signal and the evidence base for eventually removing this gate.

In the MVP every claim that clears the Tier 1 gate lands here. Nothing is
auto-approved.
"""

import hashlib
import json
import os
import shutil
from datetime import datetime, timezone

import pandas as pd
import streamlit as st

from config import (
    ADAS_CONFIDENCE_PENALTY,
    AUTHENTICITY_PENALTY,
    MAX_REQUEST_ATTEMPTS,
    OVERRIDE_LOG,
    PHASH_LEDGER,
    RUNTIME_DIR,
    TIER_STARTING_POINT_MIN,
    TIER_VERIFY_MIN,
    VLM_PROVIDER,
)
from pipeline import adas, comparables, gate, imaging, pricing, routing, run

st.set_page_config(
    page_title="AI Assisted Damage Assessment and Claim Triage",
    page_icon="🚗",
    layout="wide",
)

# Layout values the theme keys cannot reach. Kept deliberately small: these
# selectors are Streamlit internals and are the first thing to break on a
# version bump, so anything that can be done with a theme key is done there.
st.html(
    """<style>
      [data-testid="stSidebar"] { width: 296px !important; }
      /* Top padding must clear Streamlit's fixed header bar, which is 3.75rem
         tall. At 2rem the claim heading slid underneath it and was clipped.
         4.5rem is still tighter than the 6rem default. */
      .block-container { padding: 4.5rem 2.5rem 4rem; max-width: 1240px; }
    </style>"""
)

SAMPLES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "samples")

# Short, specific, mutually exclusive. Free text is optional and secondary.
REASON_CODES = [
    "wrong part",
    "wrong operation",
    "missed damage",
    "over-scoped",
    "wrong severity",
    "pricing wrong",
    "not repairable as written",
]

# Why a whole draft is not salvageable. Distinct from the line-level codes:
# those say a row is wrong, these say correcting rows would not fix it.
REJECTION_REASONS = [
    "evidence inadequate for assessment",
    "wrong vehicle or panels identified",
    "damage pattern inconsistent with the photographs",
    "too many line-level errors to correct",
    "scope fundamentally wrong",
    "requires physical or specialist inspection",
    "refer to Special Investigation Unit",
]

# Photographs per claim, and per attempt where a resubmission differs.
# CLM-1001 uses three real photographs of front corner damage; everything else
# is synthetic, and deliberately obvious about it.
SCENARIO_PHOTOS = {
    ("CLM-1001", 1): ["mazda6_front.jpg", "mazda6_corner.jpg", "mazda6_damage.jpg"],
    ("CLM-1002", 1): ["bad_blurry.jpg", "bad_dark.jpg", "bad_lowres.jpg"],
    # Deliberately empty. The re-request has gone out and nothing has come
    # back yet, so the claim sits in a waiting state until photos are uploaded.
    ("CLM-1002", 2): [],
    ("CLM-1003", 1): ["bumper_a.jpg", "bumper_b.jpg", "bumper_c.jpg"],
    ("CLM-1004", 1): ["stale_timestamp.jpg", "stale_timestamp_2.jpg"],
    ("CLM-1005", 1): ["good_a.jpg"],
    ("CLM-1006", 1): ["good_a.jpg"],
    ("CLM-1007", 1): ["sideswipe_a.jpg", "sideswipe_b.jpg", "sideswipe_c.jpg"],
}


# Generated by samples/make_samples.py. Every other file in samples/ is a real
# photograph of real damage (the Mazda and the Navigator) or derived from one.
SYNTHETIC_SAMPLES = {
    *(f"good_{a}.jpg" for a in "abc"),
    *(f"bumper_{a}.jpg" for a in "abc"),
    *(f"sideswipe_{a}.jpg" for a in "abc"),
    "stale_timestamp.jpg", "stale_timestamp_2.jpg",
}

# The photographs a policyholder sends back in answer to a re-request. A
# visitor to a hosted copy of this app does not have these files, so the
# waiting screen can load them in one click. They then run exactly as an
# upload would: counted against the views requested, screened, recorded.
SAMPLE_RESUBMISSIONS = {
    ("CLM-1002", 2): ["navigator_wheel_closeup.jpg", "navigator_wheel_angle.jpg",
                      "navigator_wheel_context.jpg"],
}


def photos_for(claim_id: str, attempt: int) -> list[str]:
    """Photos for this attempt.

    An attempt listed with no photographs is a claim awaiting a resubmission,
    which is different from an attempt nobody specified. Only the latter falls
    back to the first submission.
    """
    key = (claim_id, attempt)
    if key in SCENARIO_PHOTOS:
        return SCENARIO_PHOTOS[key]
    return SCENARIO_PHOTOS.get((claim_id, 1), [])

# (accent, tint) per routing tier. The dot and the rule carry the color; the
# pill carries the tint; badge text stays ink so the tier reads as a label
# rather than as an alarm.
TIER_STYLE = {
    "verify":         ("#2E8B6F", "#E3F1EC"),
    "starting_point": ("#C98A1A", "#F7ECD6"),
    "low_confidence": ("#B33A3A", "#F5E1E1"),
    "re_request":     ("#4A6580", "#ECF1F6"),
    "escalated":      ("#1B3247", "#DEE5EE"),
    "not_processed":  ("#B33A3A", "#F5E1E1"),
}

INK, MUTED, BORDER = "#0D1B2A", "#4A6580", "#DEE5EE"
CONFIDENCE_BAR = "#4A6580"   # magnitude, never judgment. Not the orange accent.


# --------------------------------------------------------------------------
# Tooltip text
# --------------------------------------------------------------------------
# A reviewer being asked to trust a number is entitled to know what produced
# it without leaving the screen. Every score on this page carries one of these.

HELP_CLAIM_CONFIDENCE = (
    "The composite of the four signals below, less any fixed penalties. It "
    "decides the routing tier only. No tier approves, denies or pays anything "
    "on its own.\n\n"
    "Weights and thresholds are placeholders. In production they are set by "
    "retrospective calibration against historical claims whose final cost, "
    "including any supplement, is already known."
)

HELP_LINE_ITEM_FLOOR = (
    "The lowest per-line confidence in the estimate.\n\n"
    "Each line carries the model's confidence in the determination it made for "
    "that line: that this operation, on this part, at this severity, is what "
    "the damage actually requires.\n\n"
    "The claim is anchored on the lowest of them rather than the average. Ten "
    "lines at 0.90 and one at 0.60 average 0.87; this signal reads 0.60, "
    "because one wrong line ruins an estimate, and the weak line is usually "
    "the sensor or structural item that generates the supplement.\n\n"
    "Blend lines are excluded. A blend is paint applied to an adjacent "
    "undamaged panel so the refinished panel beside it does not show a hard "
    "edge, so its confidence is a judgment about color match rather than "
    "about the damage."
)

HELP_EVIDENCE_COVERAGE = (
    "How adequately the photographs cover every damaged zone: whether each "
    "angle the assessment needs is actually present, and whether every file "
    "passes the deterministic sharpness, resolution and exposure checks.\n\n"
    "A file that fails those checks caps this signal at 0.40 regardless of "
    "what the model says about it. The measurement overrides the opinion."
)

HELP_RETRIEVAL_DENSITY = (
    "How many closely comparable historical claims exist for this vehicle, "
    "panel and damage pattern.\n\n"
    "Dense comparables mean the scope and pricing rest on precedent. Sparse "
    "comparables mean the estimate is an extrapolation and should be treated "
    "as one.\n\n"
    "Stubbed in this build: the comparables corpus is not connected, so this "
    "is approximated as the share of damaged panels that appear in the hidden "
    "damage rules table. Blend lines are left out, because a blend names an "
    "undamaged panel."
)

HELP_CROSS_STAGE_AGREEMENT = (
    "Whether the line items the damage stage identified map cleanly onto "
    "priceable operations in the costing stage.\n\n"
    "An item that cannot be priced has two possible causes. The damage stage "
    "may have named something the costing stage does not recognize, which is "
    "a stronger warning than either stage reporting low confidence on its "
    "own. Or the price catalog has a gap. Either way the total is "
    "incomplete.\n\n"
    "Against a complete production catalog the first cause dominates. "
    "Against the stub catalog in this build, gaps are more likely."
)

HELP_PENALTIES = (
    "Penalties are fixed subtractions applied after the signals are combined, "
    "not signals averaged in with them.\n\n"
    f"ADAS calibration zone touched: −{ADAS_CONFIDENCE_PENALTY:.2f}\n\n"
    "Media authenticity, scaled to the strongest flag on the claim: "
    f"strong −{AUTHENTICITY_PENALTY['strong']:.2f} (the same photo on another "
    f"claim, or taken before the loss), moderate "
    f"−{AUTHENTICITY_PENALTY['moderate']:.2f} (editing software, taken long "
    f"after the loss), weak −{AUTHENTICITY_PENALTY['weak']:.2f} (no photo "
    f"metadata). Only a strong flag bars the verify tier.\n\n"
    "Hidden damage candidates: no penalty in this build. The signal fires on "
    "nearly every claim, and weighting it without observed rates from a real "
    "claims corpus would be inventing evidence."
)

HELP_LINE_CONFIDENCE_COLUMN = (
    "The model's confidence in the determination made for this line: that this "
    "operation, on this part, at this severity, is what the damage requires. "
    "It is not a confidence in the price."
)


# --------------------------------------------------------------------------
# Sidebar
# --------------------------------------------------------------------------

with st.sidebar:
    st.title("Damage Assessment and Claim Triage")
    st.caption("AI assisted assessment and routing, between damage "
               "documentation and estimate approval.")

    # A visitor with no one to explain the demo needs a route through it.
    # Collapsed by default so it stays out of the way of a recorded walkthrough.
    with st.expander("New here? Five things to try"):
        st.markdown(
            "1. **CLM-1001**: a clean claim, **Verify** at 0.94. Hover the **?** "
            "beside each score.\n"
            "2. **CLM-1002**: attempt 1 is refused. Switch to attempt 2 and press "
            "**Use the sample resubmission photos**: **Verify** at 0.92, with "
            "four risks no photo can confirm.\n"
            "3. **CLM-1003**, then **CLM-1007**: the same sensor penalty. The "
            "Camry lands at **Starting point** (0.60), the CR-V at **Low "
            "confidence** (0.38), because it was weak before the penalty.\n"
            "4. **CLM-1004**: photos taken before the accident. Flagged, never "
            "denied. **CLM-1005/1006**: excluded before any photo is read.\n"
            "5. **Be the claims agent** on CLM-1001: edit a price or add a line. "
            "Nothing records without a reason code."
        )
        st.caption(
            "Numbers are for mock mode; live mode reads the photos and varies. "
            "Then try to break it: a blurry photo, a screenshot, a file that is "
            "not an image, or the same photo on two claims. In mock mode the "
            "line items are scripted. Loss dates are in September 2026, so a "
            "photo taken today is flagged as outside the capture window."
        )

    claims = gate.list_claims()
    labels = {cid: f"{cid}" for cid, _ in claims}
    claim_id = st.selectbox(
        "Claim", [c for c, _ in claims], format_func=lambda c: labels[c]
    )
    scenario = dict(claims).get(claim_id, "")
    if scenario:
        st.info(scenario, icon="🎬")
        if VLM_PROVIDER == "anthropic":
            if all(p in SYNTHETIC_SAMPLES
                   for p in SCENARIO_PHOTOS.get((claim_id, 1), [])):
                # Synthetic test files are never sent to the model, so the
                # scripted expectation holds in live mode too.
                st.caption("Live mode: this claim's sample images are "
                           "synthetic test files, so they are never sent to "
                           "the model and the expectation above holds.")
            else:
                # The scenario's "Expect:" is the scripted mock result. In live
                # mode the model writes its own line items, so the tier can
                # differ.
                st.caption("Live mode: the model reads the photographs and "
                           "writes its own line items, so the result can "
                           "differ from the expectation above.")

    attempt = st.radio(
        "Submission attempt", [1, 2], horizontal=True,
        help="Attempt 2 is the resubmission. On CLM-1002 it starts empty, "
             "awaiting the policyholder's photos: press Use the sample "
             "resubmission photos, or upload your own, and the claim proceeds.",
    )
    if attempt == 2 and (claim_id, 2) not in SCENARIO_PHOTOS:
        st.caption("No resubmission was requested on this claim, so attempt 2 "
                   "shows the original photographs.")

    uploaded = st.file_uploader(
        "Or upload your own photos",
        # Keyed on the claim, so switching claims clears the uploader instead
        # of silently re-attaching one claim's photographs to another. Evidence
        # belongs to the claim it was submitted against.
        key=f"upload::{claim_id}",
        # Whatever Pillow can read in this install, including HEIC when
        # pillow-heif is present. WEBP and HEIC usually arrive with EXIF
        # stripped, which the authenticity stage flags rather than ignores.
        type=imaging.supported_upload_types(),
        accept_multiple_files=True,
        help="Your photos replace the demo set and run against this claim's "
             "policy and vehicle. Quality, authenticity and confidence all "
             "measure your actual file. A photo that reached you through a "
             "messaging app or browser has usually lost its EXIF, which "
             "raises an authenticity flag.",
    )

    st.divider()
    live = VLM_PROVIDER == "anthropic"
    st.metric("Vision provider", VLM_PROVIDER.upper())
    if live:
        st.success("Live model calls", icon="🟢")
    else:
        st.warning(
            "Mock mode. Image quality, EXIF, C2PA and perceptual hashing are "
            "REAL in every mode. Damage line items are scripted. Set "
            "`VLM_PROVIDER=anthropic` with an API key for live assessment.",
            icon="🟡",
        )

    st.divider()
    with st.expander("Stubbed components"):
        st.caption(f"**Pricing** — {pricing.STUB_NOTE}")
        st.caption(f"**Comparables** — {comparables.STUB_NOTE}")
        st.caption("**Policy system** — read from a local JSON fixture.")

    SHOW_RATIONALE = st.toggle(
        "Show design rationale",
        value=False,
        help="Explains why each part of this screen works the way it does. Off "
             "by default: a claims agent needs the decision, not the argument "
             "behind it.",
    )

    # Demo state lives in runtime/, which git ignores, so it survives a pull or
    # an unzip over an existing folder. A reuse ledger left from earlier
    # testing flags photos in a new session as "previously submitted on another
    # claim", which can knock a clean claim out of its tier in front of an
    # audience, and old test overrides reappear in the log. One click clears
    # all of it before a demo.
    if st.button(
        "Reset demo data",
        help="Clears the photo reuse ledger, the override log and uploaded "
             "files. Use before a demo so nothing from earlier testing "
             "affects what is on screen.",
    ):
        for _path in (PHASH_LEDGER, OVERRIDE_LOG):
            if os.path.exists(_path):
                os.remove(_path)
        shutil.rmtree(os.path.join(RUNTIME_DIR, "uploads"), ignore_errors=True)
        for _k in [k for k in st.session_state.keys()
                   if str(k).startswith(("recorded_", "sample_resub::"))]:
            del st.session_state[_k]
        st.success("Demo data cleared.", icon="🧹")


def rationale(text):
    """Design commentary, shown only when the reviewer asks for it.

    The working surface carries what a claims agent needs to act. Why it is
    built this way belongs in the PRD, and here behind a toggle. Mixing the
    two is how a product screen turns into a pitch deck.
    """
    if SHOW_RATIONALE:
        st.caption(text)


# --------------------------------------------------------------------------
# Run the pipeline
# --------------------------------------------------------------------------

rejected_uploads = []
if uploaded:
    paths = []
    for i, f in enumerate(uploaded):
        # One folder per file, so two phones' IMG_0001.jpg cannot overwrite
        # each other and the displayed filename stays the one the user chose.
        folder = os.path.join(RUNTIME_DIR, "uploads", claim_id, f"{i:02d}")
        os.makedirs(folder, exist_ok=True)
        dest = os.path.join(folder, f.name)
        with open(dest, "wb") as fh:
            fh.write(f.getbuffer())
        why = imaging.unreadable_reason(dest)
        if why:
            rejected_uploads.append((f.name, why))
        else:
            paths.append(dest)
elif (st.session_state.get(f"sample_resub::{claim_id}::{attempt}")
      and (claim_id, attempt) in SAMPLE_RESUBMISSIONS):
    paths = [os.path.join(SAMPLES, n)
             for n in SAMPLE_RESUBMISSIONS[(claim_id, attempt)]]
else:
    paths = [os.path.join(SAMPLES, n) for n in photos_for(claim_id, attempt)]

using_sample = bool(not uploaded
                    and st.session_state.get(f"sample_resub::{claim_id}::{attempt}")
                    and (claim_id, attempt) in SAMPLE_RESUBMISSIONS)

if rejected_uploads:
    st.error(
        "**Not used:** "
        + "; ".join(f"`{name}`, {why}" for name, why in rejected_uploads)
        + ". Everything else runs as normal.",
        icon="🚫",
    )

if uploaded and not paths:
    st.markdown(f"### {claim_id} · {gate.load_claim_context(claim_id).vehicle_label}")
    st.info("None of the uploaded files could be read as an image, so nothing "
            "was assessed. Upload photographs in one of the formats the uploader lists.", icon="📎")
    st.stop()

if not paths:
    ctx_waiting = gate.load_claim_context(claim_id)
    st.markdown(f"### {claim_id} · {ctx_waiting.vehicle_label}")
    if ctx_waiting.loss_description:
        st.markdown(f"**Reported by the policyholder:** "
                    f"{ctx_waiting.loss_description}")
    st.html(
        f"""<div style="background:#FFFFFF;border:1px solid {BORDER};
        border-left:4px solid #4A6580;border-radius:10px;padding:20px 24px;
        margin:16px 0 4px 0;">
          <span style="display:inline-flex;align-items:center;gap:8px;
          background:#ECF1F6;border-radius:999px;padding:4px 12px 4px 10px;">
            <span style="width:8px;height:8px;border-radius:50%;
            background:#4A6580;display:inline-block;"></span>
            <span style="font-size:11px;font-weight:600;letter-spacing:0.12em;
            color:{INK};">AWAITING RESUBMISSION</span>
          </span>
          <div style="font-family:'Saira',system-ui,sans-serif;font-size:24px;
          font-weight:600;line-height:1.2;color:{INK};margin-top:12px;">
          Attempt {attempt} of {MAX_REQUEST_ATTEMPTS}, nothing received yet</div>
          <div style="font-size:13.5px;color:{MUTED};margin-top:6px;">
          A specific request went to the policyholder on attempt
          {attempt - 1}. No assessment runs until photographs come back.</div>
        </div>"""
    )
    st.caption(
        "**Next:** upload the resubmitted photographs in the sidebar. They run "
        "through the same pipeline: quality, authenticity, assessment, "
        "confidence and routing."
    )
    if (claim_id, attempt) in SAMPLE_RESUBMISSIONS:
        if st.button("Use the sample resubmission photos", type="primary",
                     key=f"use_sample::{claim_id}::{attempt}",
                     help="Loads the three photographs in the samples folder as "
                          "if the policyholder had sent them back: the rim face, "
                          "the sidewall, and the wheel in context."):
            st.session_state[f"sample_resub::{claim_id}::{attempt}"] = True
            st.rerun()
    if VLM_PROVIDER != "anthropic":
        st.info(
            "Without a key the damage line items come from this claim's script "
            "rather than from your photographs, so the flow is demonstrable "
            "either way. The screen says so when it happens. Set "
            "`VLM_PROVIDER=anthropic` to have the model actually read them.",
            icon="🟡",
        )
    st.stop()

# record_hashes=True: the reuse check only works if the app records what it
# has seen. It was False from the first commit, so in the app the "same photo
# on two claims" screen never fired, while the README, the PRD and this screen
# all said it did. Same-claim matches are skipped, so re-rendering a claim
# never flags its own photographs.
# A claim whose only images are synthetic test files is never sent to the live
# model. The model would rightly find no vehicle to assess and escalate, which
# says nothing about the product. Those claims use their scripted assessment in
# every mode, and the screen says so. Uploading real photographs to them runs
# them live as normal.
scripted_only = bool(
    VLM_PROVIDER == "anthropic" and not uploaded and not using_sample and paths
    and all(os.path.basename(p) in SYNTHETIC_SAMPLES for p in paths)
)

try:
    # Live answers are cached per photo set, so only the first look at a claim
    # waits on the model. Say so while it happens, rather than showing a
    # frozen page.
    if VLM_PROVIDER == "anthropic" and not scripted_only:
        with st.spinner("The model is reading the photographs. The first look "
                        "at a claim takes about 10 to 20 seconds; after that "
                        "it is instant."):
            result = run.run(
                claim_id, paths, attempt=attempt, record_hashes=True,
                user_photos=bool(uploaded) or using_sample,
            )
    else:
        result = run.run(
            claim_id, paths, attempt=attempt, record_hashes=True,
            user_photos=bool(uploaded) or using_sample,
            provider_name="mock" if scripted_only else None,
        )
except Exception as exc:
    # In live mode this is usually the vision API: a timeout, a rate limit, a
    # response that is not the JSON asked for. A presenter needs a sentence
    # and a way forward, not a stack trace.
    st.markdown(f"### {claim_id}")
    if "anthropic-workspace-id" in str(exc):
        # The one live-mode setup error with a known, specific fix.
        _hint = ("Your API key can reach more than one workspace, so the API "
                 "needs to be told which one to use. Add "
                 "`ANTHROPIC_WORKSPACE_ID=wrkspc_...` to your `.env` file (the "
                 "ID is at platform.claude.com/settings/workspaces) and restart, "
                 "or create a key limited to a single workspace.")
    elif VLM_PROVIDER == "anthropic":
        _hint = ("The vision model call failed or returned something unusable. "
                 "Try again, or set `VLM_PROVIDER=mock` to continue without it.")
    else:
        _hint = "This is a defect in the prototype, not an expected outcome."
    st.error(
        f"The assessment could not be completed: {type(exc).__name__}. {_hint}",
        icon="⚠️",
    )
    with st.expander("Technical detail"):
        st.exception(exc)
    st.stop()
ctx = result.context


# --------------------------------------------------------------------------
# Header and decision
# --------------------------------------------------------------------------

if scripted_only and result.gate_passed:
    st.info(
        "**Scripted assessment for this claim.** Its sample images are "
        "synthetic test files, not photographs of a vehicle, so they are not "
        "sent to the live model. The deterministic checks, confidence and "
        "routing all run for real. Upload real photographs to run this claim "
        "live.",
        icon="🧪",
    )
elif uploaded and not result.gate_passed:
    # The gate runs before any photograph is read. Saying "your photos are
    # being measured" above a claim that never looked at them contradicts the
    # Photos: 0 metric directly beneath it.
    st.info(
        f"**{claim_id}** is excluded at the gate, before any photograph is "
        f"read, so your {len(paths)} upload(s) were not processed. That is "
        f"the intended behavior: no compute is spent on a claim that leaves "
        f"the automated path.",
        icon="📎",
    )
elif using_sample:
    b1, b2 = st.columns([5, 1])
    with b1:
        st.info(
            "Running the **three sample resubmission photographs** as the "
            "policyholder's answer to the attempt 1 request. They go through "
            "every stage exactly as an upload would."
            + ("" if VLM_PROVIDER == "anthropic" else
               " **The damage line items are this claim's scripted assessment,** "
               "since mock mode cannot see a photograph."),
            icon="📎",
        )
    with b2:
        if st.button("Clear", key=f"clear_sample::{claim_id}::{attempt}",
                     help="Return to the waiting state."):
            del st.session_state[f"sample_resub::{claim_id}::{attempt}"]
            st.rerun()
elif uploaded:
    if VLM_PROVIDER == "anthropic":
        st.info(
            f"Running your {len(paths)} photo(s) against **{claim_id}** — its "
            f"policy, vehicle and loss date. Every stage reads your actual "
            f"files, including the model.",
            icon="📎",
        )
    else:
        st.info(
            f"Running your {len(paths)} photo(s) against **{claim_id}** — its "
            f"policy, vehicle and loss date. Image quality, EXIF, C2PA, reuse "
            f"hashing, evidence sufficiency, confidence and routing all measure "
            f"your actual files. **The damage line items are this claim's "
            f"scripted assessment, not a reading of your photographs** — mock "
            f"mode cannot see them. Set `VLM_PROVIDER=anthropic` for a real "
            f"reading.",
            icon="📎",
        )

st.markdown(f"### {claim_id} · {ctx.vehicle_label}")
c1, c2, c3, c4 = st.columns(4)
c1.metric("Loss date", ctx.loss_date.strftime("%d %b %Y"))
c2.metric("Deductible", f"${ctx.deductible:,.0f}")
c3.metric("Photos", len(result.photos))
c4.metric("ADAS data", "on file" if adas.is_known_vehicle(ctx) else "unknown vehicle")
if ctx.loss_description:
    # What the policyholder said at first notice of loss. It scopes the photo
    # check, so the reviewer should see the same context the model was given.
    st.markdown(f"**Reported by the policyholder:** {ctx.loss_description}")

decision = result.decision
tier = decision.tier
accent, tint = TIER_STYLE.get(tier, (MUTED, "#ECF1F6"))

st.html(
    f"""<div style="background:#FFFFFF;border:1px solid {BORDER};
    border-left:4px solid {accent};border-radius:10px;padding:20px 24px;
    margin:16px 0 4px 0;">
      <span style="display:inline-flex;align-items:center;gap:8px;
      background:{tint};border-radius:999px;padding:4px 12px 4px 10px;">
        <span style="width:8px;height:8px;border-radius:50%;
        background:{accent};display:inline-block;"></span>
        <span style="font-size:11px;font-weight:600;letter-spacing:0.12em;
        color:{INK};">{routing.TIER_LABELS.get(tier, tier.upper())}</span>
      </span>
      <div style="font-family:'Saira',system-ui,sans-serif;font-size:24px;
      font-weight:600;line-height:1.2;color:{INK};margin-top:12px;">
      {decision.headline}</div>
      <div style="font-size:13.5px;color:{MUTED};margin-top:6px;">
      {routing.TIER_GUIDANCE.get(tier, "")}</div>
    </div>"""
)

for reason in decision.reasons:
    st.markdown(f"- {reason}")

NEXT_STEP = {
    "verify": "**Next:** check the line items against the photographs rather "
              "than rebuilding them, then record your decision at the bottom.",
    "starting_point": "**Next:** work through the named risks below, correct "
                      "any line item that needs it, then record your decision. "
                      "Every change asks for a reason code.",
    "low_confidence": "**Next:** treat the figures as a starting list only. "
                      "Rebuild what you need, then record your decision.",
    "re_request": "**Next:** the request has gone to the policyholder. Nothing "
                  "further happens on this claim until they resubmit.",
    "escalated": "**Next:** a claims agent picks this up, with the photographs "
                 "and the reason each one could not be used.",
    "not_processed": "**Next:** this claim leaves the automated path entirely "
                     "and is handled in the normal workflow.",
}
if tier in NEXT_STEP:
    st.caption(NEXT_STEP[tier])


# --------------------------------------------------------------------------
# Tier 1 gate rejection: stop here
# --------------------------------------------------------------------------

if not result.gate_passed:
    st.divider()
    st.subheader("Why this claim was not processed")
    rationale(
        "Every Tier 1 exclusion is a legal or wasted-spend reason. None of them "
        "are 'the model might do badly' — those are handled downstream by "
        "confidence and routing. A narrow processing gate is self-confirming: "
        "if the system only ever sees easy claims it can never learn where the "
        "real boundary sits."
    )
    for r in result.gate_reasons:
        st.error(r, icon="⛔")
    st.stop()


# --------------------------------------------------------------------------
# Evidence
# --------------------------------------------------------------------------

st.divider()
st.subheader("Evidence")

cols = st.columns(min(len(result.photos), 4))
for i, photo in enumerate(result.photos):
    with cols[i % len(cols)]:
        st.image(photo.path, width='stretch')
        st.caption(f"**{photo.filename}** · {photo.width}×{photo.height}")
        if (not uploaded and not using_sample
                and photo.filename in SYNTHETIC_SAMPLES):
            # Disclosure, not commentary: always visible. These files exist so
            # the checks have something real to measure; they are not pictures
            # of the vehicle on the claim, and nobody should take them for one.
            st.caption("🧪 Synthetic test image: measured for real, but not a "
                       "photograph of this vehicle.")
        st.caption(
            f"sharpness {photo.sharpness:.0f} · brightness {photo.brightness:.0f}"
        )
        if photo.quality_issues:
            for issue in photo.quality_issues:
                st.error(issue, icon="📷")
        else:
            st.success("Quality checks passed", icon="✅")

        meta = []
        meta.append("EXIF present" if photo.exif_present else "no EXIF")
        if photo.capture_time:
            meta.append(f"captured {photo.capture_time:%d %b %Y %H:%M}")
        if photo.device:
            meta.append(photo.device)
        meta.append("C2PA present" if photo.c2pa_present else "no C2PA")
        st.caption(" · ".join(meta))

        for flag in photo.authenticity_flags:
            st.warning(flag, icon="🔍")

# The coverage score belongs here, under the files it was measured from, not
# only in the confidence panel further down. A reviewer looking at three
# photographs and deciding whether they are enough should see the system's
# answer to that question in the same place.
if result.evidence:
    ev = result.evidence
    st.markdown("")
    ec1, ec2 = st.columns([1, 3])
    with ec1:
        st.metric(
            "Evidence coverage",
            f"{ev.coverage_score:.2f}",
            help=HELP_EVIDENCE_COVERAGE,
        )
    with ec2:
        st.caption(
            f"**{len(result.photos)} file(s)** assessed · "
            f"{sum(1 for p in result.photos if p.quality_ok)} passed the "
            f"deterministic quality checks"
        )
        if ev.missing:
            st.caption("**Still missing:** " + "; ".join(ev.missing))
        else:
            st.caption(
                "No further angles requested. This score feeds claim "
                "confidence below the estimate."
            )

if result.evidence and result.evidence.status == "re_request":
    st.divider()
    st.subheader("Message sent to the policyholder")
    st.caption(f"Attempt {attempt} of {MAX_REQUEST_ATTEMPTS}. After that a person takes over.")
    rationale(
        "Specific and actionable, never 'send better photos'. J.D. Power 2025: "
        "customers rating a claims experience poor or just OK carry a 52% "
        "likelihood of switching carriers, against 4% for excellent. A vague "
        "repeated ask is where an efficiency feature destroys more value than "
        "it creates."
    )
    st.code(result.evidence.instruction, language=None, wrap_lines=True)
    st.info(
        "Damage assessment was NOT run. Assessing from photos already judged "
        "inadequate would produce a confident answer built on bad evidence, "
        "which is the exact failure this product exists to prevent.",
        icon="🛑",
    )
    st.stop()

if result.evidence and result.evidence.status == "escalate":
    st.divider()
    st.subheader("Handed to a claims agent")
    st.caption(
        f"The re-request cap of {MAX_REQUEST_ATTEMPTS} was reached. A person "
        "takes over from here, with the photographs and the reason each one "
        "could not be used."
    )
    st.error(result.evidence.escalation_reason, icon="👤")
    st.info(
        "No damage assessment was produced. The system stops rather than "
        "guessing from evidence it has already judged inadequate.",
        icon="🛑",
    )
    rationale(
        "Two attempts, then stop asking. A third request is where an "
        "efficiency feature starts damaging the relationship it was meant to "
        "protect, and the claim still needs handling either way. Knowing when "
        "to give up is a product decision, not a failure mode."
    )
    st.stop()


# --------------------------------------------------------------------------
# Risks
# --------------------------------------------------------------------------

assessment = result.assessment
adas_hits = adas.involved_zones(ctx, assessment.damage_panels)

if adas_hits or assessment.hidden_damage:
    st.divider()
    st.subheader("Risks the photos cannot resolve")

if adas_hits:
    st.markdown("**Calibration risk**")
    for line in adas.describe(adas_hits):
        st.warning(line, icon="📡")
    st.caption("No calibration line item is priced. This is a routing signal, not a charge.")
    rationale(
        "A photo cannot establish that calibration is required — the damage may "
        "be a scuff nowhere near the sensor bracket. Charging on suspicion "
        "overstates the estimate and starts disputes with shops. CCC Q3 2025: "
        "calibrations appear on 35.6% of DRP estimates, up from 26.9% year over "
        "year, and 51.5% of them show up on supplements rather than initial "
        "estimates."
    )

if assessment.hidden_damage:
    st.markdown("**Possible damage behind the visible panels**")
    for cand in assessment.hidden_damage:
        rate = (
            f"{cand.observed_rate:.0%} of comparable claims"
            if cand.observed_rate is not None
            else "rate unavailable (stubbed corpus)"
        )
        st.info(f"**{cand.part}** — {cand.rationale} _({rate})_", icon="🔧")
    st.caption("Informational. No confidence penalty is applied in the MVP.")
    rationale(
        "Without observed rates from a real claims corpus any weight would be "
        "arbitrary, and the signal fires on nearly every claim — a signal that "
        "fires on everything carries no information. Becomes rate-weighted once "
        "comparables are connected."
    )


# --------------------------------------------------------------------------
# Line items and override capture
# --------------------------------------------------------------------------

st.divider()
st.subheader("Draft estimate")
st.caption(
    f"Total \\${assessment.estimate_total:,.2f} before deductible "
    f"(\\${ctx.deductible:,.0f}). Pricing is stubbed — treat totals as illustrative."
)

# A line the costing stage could not price counts as zero in the total. Saying
# nothing would present an incomplete total as a complete one, which is the
# kind of quiet understatement that becomes a supplement.
_unpriced = [li for li in assessment.line_items if not li.priced]
if _unpriced:
    st.warning(
        f"**The total excludes {len(_unpriced)} line(s) the costing stage "
        f"could not price:** "
        + "; ".join(f"{li.operation} {li.part}" for li in _unpriced)
        + ". The real total is higher by an amount this system cannot state.",
        icon="💲",
    )

# A claim is filed before anyone knows what it costs; the assessment is what
# tells the carrier the visible damage sits under the deductible. Saying so is
# useful. Closing the claim on it is not, when the photos cannot rule out what
# is behind the panel.
if assessment.estimate_total < ctx.deductible:
    _risky = bool(assessment.hidden_damage) or bool(
        adas.involved_zones(ctx, assessment.damage_panels))
    st.info(
        f"**The visible estimate is below the \\${ctx.deductible:,.0f} "
        f"deductible, so as drafted nothing is payable.** "
        + ("The risks named above could take the repair past it once the "
           "damage is inspected, which is why this draft should not be used "
           "on its own to close the claim."
           if _risky else
           "Confirm the scope before advising the policyholder."),
        icon="🧾",
    )

original = pd.DataFrame(
    [
        {
            "operation": li.operation,
            "part": li.part,
            "panel": li.panel,
            "severity": li.severity,
            "price": li.price if li.price is not None else 0.0,
            "confidence": li.confidence,
            "priced": li.priced,
        }
        for li in assessment.line_items
    ]
)

if original.empty:
    st.warning("No line items were produced.")
    st.stop()

state_key = f"edit::{claim_id}::{attempt}"
edited = st.data_editor(
    original,
    key=state_key,
    width='stretch',
    hide_index=True,
    column_config={
        "price": st.column_config.NumberColumn("price", format="$%.2f",
                                               min_value=0.0),
        "confidence": st.column_config.ProgressColumn(
            "confidence", min_value=0.0, max_value=1.0, format="%.2f",
            color=CONFIDENCE_BAR,
            help=HELP_LINE_CONFIDENCE_COLUMN,
        ),
        "priced": st.column_config.CheckboxColumn(
            "priced", disabled=True,
            help="Whether the costing stage could price this line. Items it "
                 "cannot price feed the cross-stage agreement signal.",
        ),
        "panel": st.column_config.TextColumn("panel", disabled=True),
    },
    # Dynamic, not fixed. Two of the seven reason codes are "missed damage"
    # and "over-scoped", which are meaningless if the reviewer cannot add a
    # line the system missed or delete one it invented.
    num_rows="dynamic",
)

with st.expander("Why the model proposed each line"):
    for li in assessment.line_items:
        st.markdown(
            f"**{li.operation} — {li.part}** _(confidence {li.confidence:.2f})_  \n"
            f"{li.reasoning}"
        )
    rationale(
        "Reasoning is what makes an override meaningful. A reviewer cannot "
        "sensibly disagree with a number that carries no explanation."
    )


# --------------------------------------------------------------------------
# Confidence
# --------------------------------------------------------------------------
# Deliberately placed AFTER the estimate. Every input to this score is
# something the reviewer has now seen: the per-line confidences in the table
# above, the coverage score under the photographs, the priced column. Shown
# before the estimate it is four numbers from nowhere, and a reviewer who
# cannot trace a score has been handed an instruction rather than a signal.

st.divider()
st.subheader("Confidence in the estimate above")

conf = result.confidence
cc1, cc2 = st.columns([1, 2])
with cc1:
    st.metric(
        "Claim confidence",
        f"{conf.claim_confidence:.2f}",
        help=HELP_CLAIM_CONFIDENCE,
    )
    st.caption(
        f"verify ≥ {TIER_VERIFY_MIN:.2f} · starting point ≥ "
        f"{TIER_STARTING_POINT_MIN:.2f}"
    )
    st.caption("⚠️ Thresholds are placeholders, not calibrated.")
    rationale(
        "In production they are set by retrospective calibration against "
        "historical claims whose final cost, including any supplement, is "
        "already known. Naming a number before that data exists would be "
        "inventing a fact."
    )
with cc2:
    # Metrics rather than a dataframe, because a dataframe cannot carry a
    # per-row tooltip and every one of these four needs its own explanation.
    s1, s2 = st.columns(2)
    s3, s4 = st.columns(2)
    with s1:
        st.metric("Weakest line item", f"{conf.line_item_floor:.2f}",
                  help=HELP_LINE_ITEM_FLOOR)
    with s2:
        st.metric("Evidence coverage", f"{conf.evidence_coverage:.2f}",
                  help=HELP_EVIDENCE_COVERAGE)
    with s3:
        st.metric("Retrieval density", f"{conf.retrieval_density:.2f}",
                  help=HELP_RETRIEVAL_DENSITY)
    with s4:
        st.metric("Cross-stage agreement", f"{conf.cross_stage_agreement:.2f}",
                  help=HELP_CROSS_STAGE_AGREEMENT)

    # A penalty is subtracted after the signals are combined, not averaged in
    # with them, so showing either as a fifth signal would misdescribe the
    # arithmetic. Both are shown here rather than only inside the expander:
    # a penalty a reviewer cannot see makes the summary look like bad addition.
    penalties = []
    if conf.adas_penalty:
        penalties.append(f"ADAS calibration −{conf.adas_penalty:.2f}")
    if conf.authenticity_penalty:
        penalties.append(f"media authenticity −{conf.authenticity_penalty:.2f}")
    if penalties:
        st.caption("**Penalties applied:** " + " · ".join(penalties),
                   help=HELP_PENALTIES)
    else:
        st.caption("**No penalties applied.**", help=HELP_PENALTIES)

with st.expander("Show the arithmetic"):
    for line in conf.explanation:
        st.markdown(f"- {line}")
    st.caption(
        "Anchored on the weakest line item rather than the mean. Ten items at "
        "0.90 and one at 0.60 average 0.87; the floor reads 0.60, because one "
        "badly wrong line ruins an estimate and averaging buries it."
    )


# --- Detect changes ------------------------------------------------------
# Read the editor's own delta rather than diffing dataframes. Once rows can be
# added and deleted, positional comparison stops being meaningful: deleting
# row 1 shifts everything below it and every subsequent row reads as edited.
delta = st.session_state.get(state_key, {}) or {}


def _describe(row) -> str:
    bits = []
    for k in ("operation", "part"):
        v = row.get(k)
        if v is not None and not (isinstance(v, float) and pd.isna(v)) and str(v).strip():
            bits.append(str(v).strip())
    return " ".join(bits) or "unnamed line"


changes = []

for idx, fields in (delta.get("edited_rows") or {}).items():
    idx = int(idx)
    if idx >= len(original):
        continue
    for col, after in fields.items():
        if col not in ("operation", "part", "severity", "price"):
            continue
        before = original.at[idx, col]
        if isinstance(before, float) or isinstance(after, float):
            try:
                if abs(float(before) - float(after)) <= 0.005:
                    continue
            except (TypeError, ValueError):
                pass
        elif str(before) == str(after):
            continue
        changes.append({
            "id": f"edited:{idx}:{col}",
            "row": idx, "kind": "edited",
            "line": _describe(original.iloc[idx]),
            "field": col, "before": before, "after": after,
        })

# Added rows carry no stable id in the editor's delta, and their position
# shifts when an earlier added row is deleted, which moved a code onto the
# wrong line. They are keyed by their content instead, with an occurrence
# count for identical rows. Editing an added row after coding it clears its
# code, and asking again is right: the change being justified has changed.
_seen_added: dict[str, int] = {}
for row in (delta.get("added_rows") or []):
    label = _describe(row)
    _content = "|".join(str(row.get(k, "")) for k in
                        ("operation", "part", "panel", "severity", "price"))
    _digest = hashlib.md5(_content.encode("utf-8")).hexdigest()[:10]
    _n = _seen_added.get(_digest, 0)
    _seen_added[_digest] = _n + 1
    changes.append({
        "id": f"added:{_digest}#{_n}",
        "row": None, "kind": "added", "line": label,
        "field": "line item", "before": "—", "after": label,
    })

for idx in (delta.get("deleted_rows") or []):
    idx = int(idx)
    if idx >= len(original):
        continue
    label = _describe(original.iloc[idx])
    changes.append({
        "id": f"removed:{idx}",
        "row": idx, "kind": "removed", "line": label,
        "field": "line item", "before": label, "after": "—",
    })

if changes:
    revised = float(pd.to_numeric(edited["price"], errors="coerce").fillna(0).sum())
    delta_total = revised - assessment.estimate_total
    st.caption(
        f"Revised total **\\${revised:,.2f}** "
        f"({'+' if delta_total >= 0 else '−'}\\${abs(delta_total):,.2f} "
        f"against the draft). Pricing is stubbed — totals are illustrative."
    )

st.markdown("#### Reviewer decision")

if changes:
    st.markdown(f"**{len(changes)} change(s) pending. Each needs a reason code.**")
    rationale(
        "Reason codes are mandatory and are the point of this screen. Free text "
        "cannot be aggregated, and aggregation is what turns overrides into the "
        "evidence base for removing this gate later."
    )

# Deliberately not an st.form. A form defers reruns, so the rejection reason
# could not appear when the outcome changes and the button could not report
# what is still missing. The whole point of this surface is that the reviewer
# cannot record a decision without saying why.
reasons = {}
for i, ch in enumerate(changes):
    col_a, col_b = st.columns([2, 1])
    with col_a:
        if ch["kind"] == "added":
            st.markdown(f"**Added** · `{ch['line']}`")
        elif ch["kind"] == "removed":
            st.markdown(f"**Removed** · `{ch['line']}`")
        else:
            st.markdown(
                f"`{ch['line']}` · **{ch['field']}** "
                f"`{ch['before']}` → `{ch['after']}`"
            )
    with col_b:
        # index=None: a code the reviewer never chose is not a reason.
        # Keyed on the change's identity, not its position in the list. With
        # positional keys, adding a line and then editing a price shifted every
        # code one slot, and the log recorded the price edit as "missed damage"
        # with no visible sign. The override log is the training signal, so a
        # misattributed code is worse than a missing one.
        reasons[i] = st.selectbox(
            "reason", REASON_CODES, key=f"reason_{state_key}_{ch['id']}",
            index=None, placeholder="Choose a reason code",
            label_visibility="collapsed",
        )

action = st.radio(
    "Outcome", ["Approve as reviewed", "Approve with changes", "Reject and rebuild"],
    horizontal=True, index=None, key=f"outcome_{state_key}",
)

rejection_reason = None
if action == "Reject and rebuild":
    rejection_reason = st.selectbox(
        "Reason for rejecting the draft", REJECTION_REASONS,
        key=f"reject_{state_key}", index=None,
        placeholder="Choose a rejection reason",
        help="Rejecting a whole draft is a stronger signal than correcting "
             "a line, and it is the one the model most needs back.",
    )

note = st.text_area(
    "Optional note", placeholder="Anything the reason codes do not capture",
    height=68, key=f"note_{state_key}",
)

# What is still missing, in the order a reviewer would hit it.
missing = []
if action is None:
    missing.append("choose an outcome")
if action == "Reject and rebuild" and not rejection_reason:
    missing.append("choose a rejection reason")
if action == "Approve as reviewed" and changes:
    missing.append(f"choose Approve with changes, since {len(changes)} "
                   f"change(s) are pending, or undo them")
if action == "Approve with changes" and not changes:
    missing.append("make a change in the table, or choose Approve as reviewed")
unjustified = [i for i in range(len(changes)) if not reasons.get(i)]
if unjustified:
    missing.append(
        f"give a reason code for {len(unjustified)} change(s)"
    )
_prices = pd.to_numeric(edited["price"], errors="coerce")
if (_prices < 0).any():
    missing.append("correct the negative price")

# One record per decision. Without this a double click wrote two log lines
# for one judgment, which would count twice in any override rate.
recorded_key = f"recorded_{state_key}"
if st.session_state.get(recorded_key):
    missing = ["this decision is already recorded; use Record another "
               "decision below to start a new one"]

if missing:
    st.caption("To record: " + ", then ".join(missing) + ".")

submitted = st.button(
    "Record decision", type="primary", disabled=bool(missing),
    key=f"record_{state_key}",
)

# Unlocks this claim for another decision without touching the log. The lock
# exists to stop an accidental double click counting twice, not to stop a
# reviewer deliberately recording a second judgment.
if st.session_state.get(recorded_key) and not submitted:
    if st.button("Record another decision", key=f"again_{state_key}"):
        del st.session_state[recorded_key]
        st.rerun()

if submitted:
    os.makedirs(RUNTIME_DIR, exist_ok=True)
    record = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "claim_id": claim_id,
        "attempt": attempt,
        "vehicle": ctx.vehicle_label,
        "provider": VLM_PROVIDER,
        "claim_confidence": conf.claim_confidence,
        "routing_tier": tier,
        "adas_involved": assessment.adas_zones_involved,
        "action": action,
        "rejection_reason": rejection_reason,
        "note": note,
        "overrides": [
            {**ch, "before": str(ch["before"]), "after": str(ch["after"]),
             "reason_code": reasons[i]}
            for i, ch in enumerate(changes)
        ],
    }
    with open(OVERRIDE_LOG, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(record) + "\n")
    st.session_state[recorded_key] = True

    st.success(
        f"Recorded. {len(changes)} override(s) written to "
        f"`runtime/overrides.jsonl`.",
        icon="✅",
    )
    rationale(
        "This record is the audit trail and the calibration input. Linking "
        "predicted confidence to realized override rate is how thresholds get "
        "set, and it is the documentation the NAIC model bulletin expects, "
        "which about half of US states had adopted by 2026."
    )
    st.json(record, expanded=False)

# --- Accumulated override log -------------------------------------------
if os.path.exists(OVERRIDE_LOG):
    with st.expander("Override log"):
        # The log is a file on disk that outlives any one version of this app,
        # so a line it cannot read is skipped and counted, never allowed to
        # take down the review screen above it.
        rows, unreadable = [], 0
        with open(OVERRIDE_LOG, encoding="utf-8") as fh:
            for l in fh:
                if not l.strip():
                    continue
                try:
                    r = json.loads(l)
                except json.JSONDecodeError:
                    unreadable += 1
                    continue
                if isinstance(r, dict):
                    rows.append(r)
                else:
                    unreadable += 1
        st.caption(f"{len(rows)} decision(s) recorded so far."
                   + (f" {unreadable} unreadable line(s) skipped." if unreadable else ""))
        flat = []
        for r in rows:
            base = {"claim": r.get("claim_id", "?"),
                    "confidence": r.get("claim_confidence"),
                    "tier": r.get("routing_tier", "?")}
            overrides = r.get("overrides") or []
            if overrides:
                for o in overrides:
                    flat.append({**base, "line": o.get("line", "?"),
                                 "field": o.get("field", "?"),
                                 "reason": o.get("reason_code", "?")})
            else:
                flat.append({**base, "line": "—", "field": "—",
                             "reason": "no change"})
        if flat:
            st.dataframe(pd.DataFrame(flat), hide_index=True, width='stretch')
