"""Composite confidence.

THE PROBLEM THIS SOLVES
Ask a model how confident it is and it will give you a number. That number is
not a calibrated probability — models routinely report high confidence on
wrong answers. Since the entire plan to remove human review gates depends on
this score, it has to be built from things that can be measured.

FOUR SIGNALS
  evidence_coverage       did we get adequate angles for every damaged zone
  retrieval_density       how many close historical comparables exist
  cross_stage_agreement   do identified line items map to priceable operations
  adas_penalty            does damage touch a calibration-dependent zone

AGGREGATION
Anchored to the WEAKEST line item, not the mean. Ten items at 0.90 and one at
0.60 average 0.87; the floor reads 0.60. One badly wrong line ruins an estimate, and
averaging buries exactly the item that matters — which is usually the sensor
or structural item, i.e. the one that generates the supplement.

NOT AI
The per-item confidences come from the model. Everything here is deterministic
arithmetic over measurable inputs, so it is auditable, repeatable and tunable
by the carrier. A model deciding how much to trust another model is not
something you can explain to a regulator.

NOT CALIBRATED
Every weight and threshold in config.py is a placeholder. In production they
are set by retrospective calibration against a recent historical sample where
the final cost including any supplement is already known. This
module deliberately does not pretend otherwise.
"""

from decimal import ROUND_HALF_UP, Decimal

from config import (
    ADAS_CONFIDENCE_PENALTY,
    AUTHENTICITY_PENALTY,
    W_CROSS_STAGE_AGREEMENT,
    W_EVIDENCE_COVERAGE,
    W_LINE_ITEM_FLOOR,
    W_RETRIEVAL_DENSITY,
)
from pipeline.models import Assessment, ConfidenceBreakdown

# What each authenticity flag means, in words a reviewer reads once and
# understands. Keyed by the same prefixes authenticity.flag_strength() uses.
_FLAG_REASON = (
    ("Visually near-identical", "closely matches a photo already submitted on "
     "another claim"),
    ("Capture time predates", "was taken before the reported accident"),
    ("Image metadata declares it was generated",
     "declares in its metadata that it was generated by AI"),
    ("Image metadata declares it was edited",
     "declares in its metadata that it was edited with generative AI"),
    ("Metadata names an AI image generator",
     "names an AI image generator in its metadata"),
    ("Metadata names editing software", "was saved by photo editing software"),
    ("Capture time is", "was taken well after the reported accident"),
    ("No EXIF metadata", "has no camera metadata, so its date and device "
     "cannot be checked"),
)

_STRENGTH_NOTE = {
    "strong": "That is a strong signal, so this claim cannot be marked verify.",
    "moderate": "That is a moderate signal: worth a look, often innocent.",
    "weak": "That is a weak signal: messaging apps remove this data from most "
            "photos.",
}


def _flag_reason(flag: str) -> str:
    for prefix, reason in _FLAG_REASON:
        if flag.startswith(prefix):
            return reason
    return "raised a media authenticity flag"


def _d(x: float) -> Decimal:
    return Decimal(repr(float(x)))


def _fmt(x: Decimal) -> str:
    return f"{x:.2f}"


def compute(
    assessment: Assessment,
    evidence_coverage: float,
    retrieval_density: float,
    cross_stage_agreement: float,
    adas_hits: list[dict],
    authenticity_flags: list[str],
) -> ConfidenceBreakdown:
    explanation: list[str] = []

    # --- Base: weighted blend, anchored on the weakest line -------------
    #
    # BLEND LINES ARE EXCLUDED FROM THE FLOOR.
    #
    # A 'blend' names an ADJACENT UNDAMAGED panel that gets paint only so the
    # refinished panel next to it does not show a hard edge. Its confidence is
    # a judgment about color match, not about the damage.
    #
    # Left in, it routinely becomes the weakest line and sets the confidence
    # for the whole claim. On CLM-1001 the blend sits at 0.86 and carries
    # $80.60 of a $1,061.20 estimate, while the $831.80 bumper replacement at
    # 0.90 has no influence at all. The score would then be governed by the
    # least consequential line in the file.
    #
    # The asymmetry is the justification. A wrong blend call costs an $80 paint
    # operation that a shop corrects without a supplement. A wrong replace call
    # is the kind of error this product exists to catch.
    #
    # run.py already excludes blends from the panel set fed to retrieval
    # density, for the same underlying reason: a blend names a panel that is
    # not damaged. This makes the two treatments consistent.
    scoring_items = [li for li in assessment.line_items
                     if li.operation.lower() != "blend"]

    # An estimate of nothing but blends should not score 1.0 by default, so
    # fall back to the full set rather than to an empty one.
    if not scoring_items:
        scoring_items = list(assessment.line_items)

    if scoring_items:
        floor = min(li.confidence for li in scoring_items)
        weakest = min(scoring_items, key=lambda li: li.confidence)
        excluded = len(assessment.line_items) - len(scoring_items)
        note = (
            f" {excluded} blend line(s) excluded: a blend is paint on an "
            f"undamaged panel for color match, so its confidence is not a "
            f"judgment about the damage."
            if excluded else ""
        )
        explanation.append(
            f"Weakest line item: '{weakest.operation} {weakest.part}' at "
            f"{floor:.2f}. The score starts from the weakest line, not the "
            f"average, because one wrong line ruins an estimate.{note}"
        )
    else:
        floor = 0.0
        explanation.append("No line items produced; confidence floor is 0.")

    # Scores are stated to two decimals, the precision the thresholds use, and
    # routing uses the value shown. Two defects this prevents: floats rounded
    # separately showed "0.863 - 0.05 = 0.812" (the base was 0.8625, the
    # result 0.8125), so the arithmetic looked wrong on screen; and a claim at
    # 0.7950 would have displayed as 0.80 while routing below verify. Penalties
    # are whole hundredths, so rounding the base and then subtracting always
    # agrees with what is shown.
    exact = (
        _d(W_LINE_ITEM_FLOOR) * _d(floor)
        + _d(W_EVIDENCE_COVERAGE) * _d(evidence_coverage)
        + _d(W_RETRIEVAL_DENSITY) * _d(retrieval_density)
        + _d(W_CROSS_STAGE_AGREEMENT) * _d(cross_stage_agreement)
    ).quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP)
    base = exact.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    explanation.append(
        f"Base score = {W_LINE_ITEM_FLOOR} × weakest line {floor:.2f} + "
        f"{W_EVIDENCE_COVERAGE} × coverage {evidence_coverage:.2f} + "
        f"{W_RETRIEVAL_DENSITY} × retrieval {retrieval_density:.2f} + "
        f"{W_CROSS_STAGE_AGREEMENT} × agreement {cross_stage_agreement:.2f} "
        + (f"= {_fmt(base)}" if exact == base
           else f"= {exact:.4f}, which rounds to {_fmt(base)}")
    )

    score = base
    subtractions: list[str] = []
    notes: list[str] = []

    # --- ADAS penalty ----------------------------------------------------
    adas_penalty = 0.0
    if adas_hits:
        adas_penalty = ADAS_CONFIDENCE_PENALTY
        score -= _d(adas_penalty)
        subtractions.append(f"{adas_penalty:.2f}")
        panels = ", ".join(h["panel"].replace("_", " ") for h in adas_hits)
        explanation.append(
            f"Minus {adas_penalty:.2f} for sensor calibration risk. The damage "
            f"touches the {panels}, which "
            f"{'carries' if len(adas_hits) == 1 else 'carry'} sensors on this "
            f"vehicle. Photographs cannot show whether recalibration is needed, "
            f"and 51.5% of calibrations industry-wide appear only on "
            f"supplements, not on the first estimate."
        )

    # --- Hidden damage candidates ----------------------------------------
    # DELIBERATELY NOT PENALIZED IN THE MVP.
    #
    # Nearly every damage pattern has candidates behind it, so a flat penalty
    # fires on almost every claim — and a signal that fires on everything
    # carries no information. It simply shifts the whole distribution down and
    # collapses the routing tiers.
    #
    # Weighting it properly requires OBSERVED RATES from a real claims corpus
    # ("38% of 340 comparable claims involved radiator support damage"). The
    # stub has no rates, and inventing weights would be fabricating evidence.
    #
    # So in the MVP these are surfaced to the reviewer as information, and the
    # penalty is switched on — rate-weighted — once comparables are real.
    if assessment.hidden_damage:
        notes.append(
            f"Not scored: {len(assessment.hidden_damage)} hidden damage "
            f"candidate(s) are shown to the reviewer for information only. "
            f"Without observed rates from a real claims corpus any weight would "
            f"be arbitrary, and the signal fires on nearly every claim. It "
            f"becomes rate-weighted when comparables are connected."
        )

    # --- Authenticity -----------------------------------------------------
    authenticity_penalty = 0.0
    if authenticity_flags:
        from pipeline.authenticity import flag_strength
        strongest = max((flag_strength(f) for f in authenticity_flags),
                        key=lambda s: AUTHENTICITY_PENALTY[s])
        authenticity_penalty = AUTHENTICITY_PENALTY[strongest]
        score -= _d(authenticity_penalty)
        subtractions.append(f"{authenticity_penalty:.2f}")
        # Flags arrive de-duplicated across photos, so the count of photos
        # behind a flag is not known here. "At least one" is always true.
        top = next(f for f in authenticity_flags if flag_strength(f) == strongest)
        explanation.append(
            f"Minus {authenticity_penalty:.2f} for media authenticity. At least "
            f"one photo {_flag_reason(top)} (see the photo cards above). "
            f"{_STRENGTH_NOTE[strongest]} Only the most serious flag on a claim "
            f"counts, and a flag never denies a claim."
        )

    score = max(Decimal("0"), min(Decimal("1"), score))
    if subtractions:
        explanation.append(
            f"Claim confidence = {_fmt(base)} − {' − '.join(subtractions)} "
            f"= {_fmt(score)}"
            + (" (a score cannot go below zero)" if score == 0 else "")
        )
    else:
        explanation.append(
            f"Claim confidence = {_fmt(score)} (no penalties applied)")
    explanation.extend(notes)
    score = float(score)

    return ConfidenceBreakdown(
        evidence_coverage=round(evidence_coverage, 3),
        retrieval_density=round(retrieval_density, 3),
        cross_stage_agreement=round(cross_stage_agreement, 3),
        adas_penalty=round(adas_penalty, 3),
        authenticity_penalty=round(authenticity_penalty, 3),
        line_item_floor=round(floor, 3),
        claim_confidence=round(score, 2),
        explanation=explanation,
    )
