"""Generate the synthetic and derived test images.

What this makes:
  good_a/b/c.jpg  synthetic scenes for CLM-1005 and CLM-1006. Both claims are
                  excluded at the gate, so their photos are never read.
  bad_*.jpg       CLM-1002 attempt 1, made from the real Navigator photographs:
                  blurred, darkened and shrunk, so the quality gate fails for
                  real, measured reasons rather than simulated ones.

What it does not make: the images for CLM-1003, CLM-1004, CLM-1007 and
CLM-1008. Those were generated by Google's image model and are committed as
files. The README says what was done to each.

WHY EACH CLAIM GETS ITS OWN COMPOSITION
---------------------------------------
A perceptual hash is a signature of an image's LOW-FREQUENCY LUMINANCE LAYOUT:
where the light and dark regions sit, at roughly 32x32 resolution. It ignores
fine detail almost entirely, which is the whole point, since that is what makes
it survive resizing and recompression.

The first version of this file drew every sample from one composition and
varied only a random speckle pattern. Speckle is high-frequency, so it does not
move the hash at all. The result was that all fourteen synthetic files hashed
to within the duplicate threshold of one another, and two of them were at
distance ZERO.

The authenticity screen flags a photo when it is near-identical to one already
recorded against a DIFFERENT claim. With every sample colliding, the flag fired
on whichever scripted claim was opened second, third and fourth, purely as a
function of click order. That put a fraud flag on the Camry and dropped its
confidence from 0.60 to 0.40, contradicting the worked example in the PRD.

So each claim's synthetic photographs got their own SCENE: a different panel
geometry, damage position, hatch direction and tonal layout. Within a claim the
images stay similar, which is correct, because three angles of one dent should
look alike, and the screen skips same-claim comparisons anyway. Only the good_*
set is still drawn this way.

ui_test.py asserts that no two samples belonging to different claims fall
within the duplicate threshold, so this cannot silently come back.
"""
import os
import random
from datetime import datetime, timedelta

from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))


def scene(seed: int, w=1600, h=1200, bg=(120, 125, 132)):
    """One composition. The same seed always yields the same layout.

    Everything varied here is large-scale on purpose: panel position and size,
    where the damage sits, which way the scratches run, and where the broad
    light and dark bands fall. Those are the things a perceptual hash actually
    sees.
    """
    rng = random.Random(seed)
    img = Image.new("RGB", (w, h), bg)
    d = ImageDraw.Draw(img)

    # Panel: position and proportions differ per scene.
    mx = int(w * rng.uniform(0.05, 0.16))
    my = int(h * rng.uniform(0.12, 0.26))
    panel = (rng.randint(36, 74), rng.randint(52, 96), rng.randint(74, 128))
    d.rounded_rectangle([mx, my, w - mx, h - my],
                        radius=max(8, w // rng.randint(18, 34)), fill=panel)

    # Broad tonal bands. These carry most of the hash, so their orientation and
    # placement are what actually separates one scene from another.
    for _ in range(rng.randint(2, 4)):
        if rng.random() < 0.5:
            y0 = rng.randint(my, h - my - 80)
            d.rectangle([mx, y0, w - mx, y0 + rng.randint(60, 190)],
                        fill=tuple(min(255, c + rng.randint(22, 58)) for c in panel))
        else:
            x0 = rng.randint(mx, w - mx - 80)
            d.rectangle([x0, my, x0 + rng.randint(60, 190), h - my],
                        fill=tuple(max(0, c - rng.randint(18, 46)) for c in panel))

    # Damage region, placed away from center so scenes do not converge.
    cx = int(w * rng.uniform(0.28, 0.72))
    cy = int(h * rng.uniform(0.32, 0.68))
    rx, ry = int(w * rng.uniform(0.08, 0.17)), int(h * rng.uniform(0.07, 0.15))
    d.ellipse([cx - rx, cy - ry, cx + rx, cy + ry],
              fill=tuple(min(255, c + rng.randint(30, 70)) for c in panel))

    # Scratches. Direction flips per scene, which moves the hash further.
    step = max(4, rx // rng.randint(6, 12))
    down = rng.random() < 0.5
    for i in range(rng.randint(12, 24)):
        x0 = cx - rx + i * step
        y0 = cy - int(ry * 0.7) if down else cy + int(ry * 0.7)
        y1 = cy + int(ry * 0.75) if down else cy - int(ry * 0.75)
        d.line([(x0, y0), (x0 + step * 3, y1)],
               fill=(196, 202, 210), width=max(1, w // 800))

    # Fine speckle. Gives the sharpness measure real edges to find. It does not
    # affect the perceptual hash, which is exactly why it cannot be relied on
    # to separate scenes.
    for _ in range(900):
        x = rng.randint(mx + 20, w - mx - 20)
        y = rng.randint(my + 20, h - my - 20)
        d.point((x, y), fill=(rng.randint(0, 255),) * 3)

    return img


def save(img, name, exif_dt=None):
    path = os.path.join(HERE, name)
    kwargs = {"quality": 92}
    if exif_dt:
        ex = Image.Exif()
        ex[271] = "DemoPhone"                              # Make
        ex[272] = "Model X"                                # Model
        ex[306] = exif_dt.strftime("%Y:%m:%d %H:%M:%S")    # DateTime
        ex[36867] = exif_dt.strftime("%Y:%m:%d %H:%M:%S")  # DateTimeOriginal
        kwargs["exif"] = ex
    img.save(path, **kwargs)
    return path


# Chosen so the scene clears the duplicate threshold against every other
# claim's photos. ui_test.py verifies it.
SEED_GOOD = 101

# 1. Good photos for the clean path (fallback set)
for i, ang in enumerate(["a", "b", "c"], 1):
    save(scene(SEED_GOOD + i), f"good_{ang}.jpg",
         exif_dt=datetime(2026, 9, 14, 14, 20) + timedelta(minutes=i))

# 2 to 4. CLM-1002 attempt 1: the policyholder's first, unusable submission.
# Built from the real Navigator photographs rather than synthetic scenes, so
# the claim tells one story: the same wheel, photographed badly the first
# time (blurred, too dark, too small), then properly on the resubmission.
# Each fails a deterministic check for a reason a reader can see; the dark
# one also measures as soft, as dusk photos usually do.
# All three share CLM-1002 with the good photos, and the reuse screen skips
# same-claim matches, so these near-duplicates never flag.
NAV = {n: os.path.join(HERE, f"navigator_wheel_{n}.jpg")
       for n in ("closeup", "angle", "context")}


def _plain(path):
    with Image.open(path) as im:
        return im.convert("RGB").copy()


# Blurred: camera moved, or focus missed. Fails sharpness.
save(_plain(NAV["angle"]).filter(ImageFilter.GaussianBlur(14)), "bad_blurry.jpg",
     exif_dt=datetime(2026, 9, 20, 18, 5))

# Too dark: taken at dusk without a light. Fails brightness, and sharpness.
save(_plain(NAV["context"]).point(lambda p: int(p * 0.17)), "bad_dark.jpg",
     exif_dt=datetime(2026, 9, 20, 19, 40))

# Too small: a thumbnail forwarded from a messaging app. Fails resolution.
save(_plain(NAV["closeup"]).resize((390, 520), Image.LANCZOS), "bad_lowres.jpg",
     exif_dt=datetime(2026, 9, 20, 18, 9))

print("Generated:")
for f in sorted(os.listdir(HERE)):
    if f.endswith(".jpg"):
        print("  ", f)
